name: ci

on:
  push:
    branches: [ main ]

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest service image
        with:
          github-push-secret: ${{secrets.CR_PAT}}
          docker-image-name: lena-manager-openshift
          docker-image-tag: latest # optional
          dockerfile-path: ./Dockerfile # optional